-- Creating a user for each microservice. Each one has an independent db/schema
-- To be executed as the first init script
DECLARE
USER_EXISTS INTEGER;
BEGIN
  SELECT COUNT(*) INTO USER_EXISTS FROM DBA_USERS WHERE USERNAME='SHL_ITEM';
  IF (USER_EXISTS = 0) THEN
    EXECUTE IMMEDIATE 'CREATE USER SHL_ITEM IDENTIFIED BY "123456" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP"';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES TO SHL_ITEM';
  END IF;
  
  SELECT COUNT(*) INTO USER_EXISTS FROM DBA_USERS WHERE USERNAME='SHL_SHOPPING_LIST';
  IF (USER_EXISTS = 0) THEN
    EXECUTE IMMEDIATE 'CREATE USER SHL_SHOPPING_LIST IDENTIFIED BY "123456" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP"';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES TO SHL_SHOPPING_LIST';
  END IF;
  
  SELECT COUNT(*) INTO USER_EXISTS FROM DBA_USERS WHERE USERNAME='SHL_USER';
  IF (USER_EXISTS = 0) THEN
    EXECUTE IMMEDIATE 'CREATE USER SHL_USER IDENTIFIED BY "123456" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP"';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES TO SHL_USER';
  END IF;
  
END;

--DROP USER SHL_ITEM CASCADE;
--DROP USER SHL_SHOPPING_LIST CASCADE;
--DROP USER SHL_USER CASCADE;

--CREATE USER SHL_ITEM IDENTIFIED BY "123456" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
--GRANT ALL PRIVILEGES TO SHL_ITEM; -- comment it for 12c or higher IDENTIFIED BY "123456";

--CREATE USER SHL_SHOPPING_LIST IDENTIFIED BY "123456" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
--GRANT ALL PRIVILEGES TO SHL_SHOPPING_LIST;-- comment it for 12c or higher IDENTIFIED BY "123456";
--
--CREATE USER SHL_USER IDENTIFIED BY "123456" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
--GRANT ALL PRIVILEGES TO SHL_USER; -- comment it for 12c or higher IDENTIFIED BY "123456";