
-- Specify the report type

CREATE TABLE REP_TYPE 
(
  ID NUMBER(8, 0) NOT NULL 
, CODE VARCHAR2(50 CHAR) NOT NULL 
, DESCRIPTION VARCHAR2(255 CHAR) 
, CONSTRAINT REP_TYPE_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX REP_TYPE_PK ON REP_TYPE (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

COMMENT ON TABLE REP_TYPE IS 'This table contains all report types related to the supervisor dashboard';

COMMENT ON COLUMN REP_TYPE.ID IS 'The report type identifier';

COMMENT ON COLUMN REP_TYPE.CODE IS 'The code e.g. weekly monthly-A montly-B';

COMMENT ON COLUMN REP_TYPE.DESCRIPTION IS 'An useful description';


-- Host per report configuration 

CREATE TABLE REP_REPORT_CONFIG 
(
  ID NUMBER(8, 0) NOT NULL 
, NAME VARCHAR2(100 CHAR) NOT NULL 
, DESCRIPTION VARCHAR2(255 CHAR) 
, REPORT_QUERY CLOB NOT NULL 
, REPORT_TYPE_ID NUMBER(8, 0) NOT NULL 
, CONSTRAINT REP_REPORT_CONFIG_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX REP_REPORT_CONFIG_PK ON REP_REPORT_CONFIG (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL 
LOB (REPORT_QUERY) STORE AS SYS_LOB0000097001C00004$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  NOCACHE 
  LOGGING 
  TABLESPACE USERS 
  STORAGE 
  ( 
    INITIAL 106496 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

ALTER TABLE REP_REPORT_CONFIG
ADD CONSTRAINT REP_REPORT_TYPE_FK FOREIGN KEY
(
  REPORT_TYPE_ID
)
REFERENCES REP_TYPE
(
  ID 
)
ENABLE;

COMMENT ON TABLE REP_REPORT_CONFIG IS 'Table containing the configuration for each kind of report';

COMMENT ON COLUMN REP_REPORT_CONFIG.ID IS 'The report configuration identifier';

COMMENT ON COLUMN REP_REPORT_CONFIG.NAME IS 'The report name';

COMMENT ON COLUMN REP_REPORT_CONFIG.DESCRIPTION IS 'An useful description';

COMMENT ON COLUMN REP_REPORT_CONFIG.REPORT_QUERY IS 'The report query. The report results are based on it';

COMMENT ON COLUMN REP_REPORT_CONFIG.REPORT_TYPE_ID IS 'The report type. Cons: REP_TYPE Foreign Key ';


-- To persist the data related to already generated reports

CREATE TABLE REP_OUTPUT 
(
  ID NUMBER(8, 0) NOT NULL 
, REP_NAME VARCHAR2(255 CHAR) 
, REP_CREATION_DT DATE 
, REP_FILE_REF VARCHAR2(50 CHAR) 
, REPORT_CONFIG_ID NUMBER(8, 0) 
, CONSTRAINT REP_OUT_REP_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX REP_OUT_REP_PK ON REP_OUTPUT (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE REP_OUTPUT
ADD CONSTRAINT REP_REPORT_CONFIG_FK FOREIGN KEY
(
  REPORT_CONFIG_ID
)
REFERENCES REP_REPORT_CONFIG
(
  ID 
)
ENABLE;

COMMENT ON TABLE REP_OUTPUT IS 'To persist the data related to already generated reports';

COMMENT ON COLUMN REP_OUTPUT.ID IS 'The generated report identifier';

COMMENT ON COLUMN REP_OUTPUT.REP_NAME IS 'The report name';

COMMENT ON COLUMN REP_OUTPUT.REP_CREATION_DT IS 'The generated report date';

COMMENT ON COLUMN REP_OUTPUT.REP_FILE_REF IS 'Jcr repository file identifier ';

COMMENT ON COLUMN REP_OUTPUT.REPORT_CONFIG_ID IS 'FK for report configuration';

CREATE SEQUENCE REP_TYPE_SEQ
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1;
  
 CREATE SEQUENCE REP_OUTPUT_SEQ
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1;
  
CREATE SEQUENCE REP_REPORT_CONFIG_SEQ
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1;